### ISSUE TITLE
play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector

### ISSUE THREAD

**Issue by heyinhenu** [playcommunity/play-community#1]
你好，我在按照说明配置后出现如下情况，能有人帮我解决下吗？ 个人企鹅：2567782485.

play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.util.concurrent.TimeoutException: Futures timed out after [60 seconds]
  at services.InitializeService.<init>(InitializeService.scala:36)
  at Module.configure(Module.scala:9) (via modules: com.google.inject.util.Modules$OverrideModule -> Module)
  while locating services.InitializeService

1 error]
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:186)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:124)
	at play.core.server.netty.PlayRequestHandler.modelConversion(PlayRequestHandler.scala:70)
	at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:81)
	at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:184)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129)
	at com.typesafe.netty.http.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:96)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.util.concurrent.TimeoutException: Futures timed out after [60 seconds]
  at services.InitializeService.<init>(InitializeService.scala:36)
  at Module.configure(Module.scala:9) (via modules: com.google.inject.util.Modules$OverrideModule -> Module)
  while locating services.InitializeService

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:174)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [60 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:142)
	at services.InitializeService.<init>(InitializeService.scala:84)
	at services.InitializeService$$FastClassByGuice$$eb0b4755.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)

**Comment by joymufeng** [comment]
application.conf文件的ElasticSearch配置贴出来看一下，类似下面这样的配置：
```
# 配置ElasticSearch
es {
   esIndexName = "community"
   useExternalES = false
   externalESServer = "127.0.0.1:9200"
 }
```

**Comment by joymufeng** [comment]
@heyinhenu 安装文档已更新，请参考[README.md](https://github.com/playcommunity/play-community/blob/master/README.md)。

**Comment by heyinhenu** [comment]
@joymufeng  好的 非常感谢，可能时邮件配置等哪个地方出错了， es我已经启动服务了，我下班回去再看看（工作机和上网机不一样，上网机没有权限）

**Comment by heyinhenu** [comment]
可以了 非常感谢，今天update下了
